import { Product } from '@/types';

export const flashSaleProducts: Product[] = [
  {
    id: 1,
    name: 'Gaming Laptop',
    description: 'High-performance gaming laptop with RTX 4060',
    price: 25000000,
    imageUrl: 'https://via.placeholder.com/400x400/FF6B6B/FFFFFF?text=Gaming+Laptop',
    category: 'Electronics',
    stock: 10,
    rating: 4.8,
    reviews: 256,
  },
  {
    id: 2,
    name: 'Wireless Headphones',
    description: 'Noise-cancelling wireless headphones',
    price: 3500000,
    imageUrl: 'https://via.placeholder.com/400x400/4ECDC4/FFFFFF?text=Headphones',
    category: 'Electronics',
    stock: 25,
    rating: 4.6,
    reviews: 189,
  },
  {
    id: 3,
    name: 'Smart Watch Pro',
    description: 'Fitness tracking smartwatch with GPS',
    price: 5000000,
    imageUrl: 'https://via.placeholder.com/400x400/45B7D1/FFFFFF?text=Smart+Watch',
    category: 'Electronics',
    stock: 15,
    rating: 4.7,
    reviews: 342,
  },
  {
    id: 4,
    name: 'Mechanical Keyboard',
    description: 'RGB mechanical keyboard with blue switches',
    price: 2000000,
    imageUrl: 'https://via.placeholder.com/400x400/96CEB4/FFFFFF?text=Keyboard',
    category: 'Electronics',
    stock: 30,
    rating: 4.5,
    reviews: 128,
  },
];

export const bestSellerProducts: Product[] = [
  {
    id: 5,
    name: 'iPhone 15 Pro Max',
    description: 'Latest iPhone model with A17 Pro chip',
    price: 29000000,
    imageUrl: 'https://via.placeholder.com/400x400/007AFF/FFFFFF?text=iPhone+15',
    category: 'Electronics',
    stock: 20,
    rating: 4.9,
    reviews: 512,
  },
  {
    id: 6,
    name: 'AirPods Pro 2',
    description: 'Wireless earbuds with active noise cancellation',
    price: 6000000,
    imageUrl: 'https://via.placeholder.com/400x400/34C759/FFFFFF?text=AirPods',
    category: 'Electronics',
    stock: 50,
    rating: 4.8,
    reviews: 423,
  },
  {
    id: 7,
    name: 'iPad Air M2',
    description: 'Powerful tablet with M2 chip',
    price: 15000000,
    imageUrl: 'https://via.placeholder.com/400x400/FF9500/FFFFFF?text=iPad+Air',
    category: 'Electronics',
    stock: 15,
    rating: 4.7,
    reviews: 298,
  },
  {
    id: 8,
    name: 'MacBook Air M2',
    description: 'Thin and light laptop with M2 chip',
    price: 28000000,
    imageUrl: 'https://via.placeholder.com/400x400/5856D6/FFFFFF?text=MacBook',
    category: 'Electronics',
    stock: 10,
    rating: 4.9,
    reviews: 367,
  },
];

export const newArrivalProducts: Product[] = [
  {
    id: 9,
    name: 'Sony WH-1000XM5',
    description: 'Premium noise-cancelling headphones',
    price: 8000000,
    imageUrl: 'https://via.placeholder.com/400x400/FF2D55/FFFFFF?text=Sony+XM5',
    category: 'Electronics',
    stock: 18,
    rating: 4.8,
    reviews: 145,
  },
  {
    id: 10,
    name: 'Samsung Galaxy S24 Ultra',
    description: 'Latest flagship phone with S Pen',
    price: 22000000,
    imageUrl: 'https://via.placeholder.com/400x400/AF52DE/FFFFFF?text=Galaxy+S24',
    category: 'Electronics',
    stock: 25,
    rating: 4.7,
    reviews: 234,
  },
  {
    id: 11,
    name: 'DJI Mini 4 Pro',
    description: 'Compact drone with 4K camera',
    price: 18000000,
    imageUrl: 'https://via.placeholder.com/400x400/32ADE6/FFFFFF?text=DJI+Mini',
    category: 'Electronics',
    stock: 12,
    rating: 4.9,
    reviews: 87,
  },
  {
    id: 12,
    name: 'GoPro Hero 12 Black',
    description: '5.3K action camera with image stabilization',
    price: 9500000,
    imageUrl: 'https://via.placeholder.com/400x400/00C7BE/FFFFFF?text=GoPro+12',
    category: 'Electronics',
    stock: 20,
    rating: 4.6,
    reviews: 156,
  },
];

export const explorerProducts: Product[] = [
  {
    id: 13,
    name: 'Logitech MX Master 3S',
    description: 'Wireless ergonomic mouse',
    price: 2500000,
    imageUrl: 'https://via.placeholder.com/400x400/FF9500/FFFFFF?text=MX+Master',
    category: 'Accessories',
    stock: 35,
    rating: 4.8,
    reviews: 412,
  },
  {
    id: 14,
    name: 'Dell UltraSharp 27" 4K',
    description: '4K USB-C monitor',
    price: 12000000,
    imageUrl: 'https://via.placeholder.com/400x400/5856D6/FFFFFF?text=Monitor',
    category: 'Electronics',
    stock: 15,
    rating: 4.7,
    reviews: 189,
  },
  {
    id: 15,
    name: 'Razer BlackWidow V3',
    description: 'Mechanical gaming keyboard',
    price: 3500000,
    imageUrl: 'https://via.placeholder.com/400x400/30D158/FFFFFF?text=Keyboard',
    category: 'Accessories',
    stock: 28,
    rating: 4.6,
    reviews: 267,
  },
  {
    id: 16,
    name: 'Logitech Brio 4K',
    description: 'Professional 4K webcam',
    price: 4000000,
    imageUrl: 'https://via.placeholder.com/400x400/FF375F/FFFFFF?text=Webcam',
    category: 'Electronics',
    stock: 22,
    rating: 4.5,
    reviews: 134,
  },
];
